### ISSUE TITLE
Getting started with Kibana

### ISSUE THREAD

**Issue by plaindocs** [grimoirelab/training#2]
Hi again,

This one is less of a technical bug than something missing in the flow. I install kibana and elastic search, can load commits into elastic search, but:

Index Patterns: Please specify a default index pattern
![kibana](https://cloud.githubusercontent.com/assets/95874/23690131/d94bfa98-03f1-11e7-8308-bbdd1c7a1047.png)

And I'm not sure how to fix this.

I tried editing the index to `commits*` but as the save button on the welcome screen and in the settings is not enabled, nothing works.

Any suggestions?

**Comment by jgbarah** [comment]
I see. I guess this happens when you have no index pattern in Kibana, which is normal in this case, because you're starting to use it. You should:

* Create an index pattern for commits. In that form that you're screenshotting, just use "commits" as the name ("Index name or pattern"), then you will see a menu with the date fields in the index (you can select author_date, for example), and just create the index.

* I don't remember if the first index is considered the index by default, but I guess it is. If that's the case, you're done. If not, you should just go to the index pattern page, and select it as default.

Please let me know if that works...

**Comment by mbbroberg** [comment]
Hey @plaindocs, FWIW I used `*` in that space and then imported [this dashboard](https://raw.githubusercontent.com/jgbarah/GrimoireLab-training/master/grimoireelk/dashboards/git-dashboard.json) to explore commits. I'm new to ES/Kibana, but found you can add further Index Patterns in the management tab. 


<img width="1280" alt="screen shot 2017-06-07 at 11 20 36 am" src="https://user-images.githubusercontent.com/1744971/26894459-5928be22-4b73-11e7-81cf-1772e8144374.png">

**Comment by jgbarah** [comment]
Thanks for your comments. I think we can close this. Please reopen if you feel like that.
